# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrLi′s
author:
  name: BrLi
  email: brli [at] chakralinux.org
description: > # this means to ignore newlines until "baseurl:"
  This site is created because I′m quite bored, and have just read about
  how to create custom site with github and Jekyll.<br>
  I′ll take this site as simple promotion about what I′m doing now and some
  daily digest.
show_excerpts: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brli.github.io" # the base hostname & protocol for your site
twitter_username: 131273y37848
gitlab_username:  brli7848
google_analytics: UA-41471230-4

minima:
  social_links:
    # - { platform: devto,          user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/brli" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    # - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       user_url: "https://t.me/jekyll" }
    # - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

header_pages:
  - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
markdown: kramdown
